[2019-04-29 10:31:19,657] {models.py:1359} INFO - Dependencies all met for <TaskInstance: play_with_python_op.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 10:31:19,659] {models.py:1359} INFO - Dependencies all met for <TaskInstance: play_with_python_op.detect 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 10:31:19,659] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-04-29 10:31:19,668] {models.py:1593} INFO - Executing <Task(S3KeySensor): detect> on 2019-04-28T00:00:00+00:00
[2019-04-29 10:31:19,668] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run play_with_python_op detect 2019-04-28T00:00:00+00:00 --job_id 120 --raw -sd DAGS_FOLDER/python_operator_challenge.py --cfg_path /tmp/tmpbi2hkkqg']
[2019-04-29 10:31:20,132] {base_task_runner.py:101} INFO - Job 120: Subtask detect [2019-04-29 10:31:20,132] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 10:31:20,282] {base_task_runner.py:101} INFO - Job 120: Subtask detect [2019-04-29 10:31:20,282] {models.py:273} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/python_operator_challenge.py
[2019-04-29 10:31:20,316] {base_task_runner.py:101} INFO - Job 120: Subtask detect [2019-04-29 10:31:20,316] {cli.py:520} INFO - Running <TaskInstance: play_with_python_op.detect 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 10:31:20,358] {s3_key_sensor.py:88} INFO - Poking for key : s3://cscie29-data/pset5/yelp_data/yelp_subset_1.csv
[2019-04-29 10:31:20,374] {logging_mixin.py:95} INFO - [2019-04-29 10:31:20,373] {credentials.py:1046} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-04-29 10:31:20,778] {base_sensor_operator.py:113} INFO - Success criteria met. Exiting.
[2019-04-29 10:31:24,669] {logging_mixin.py:95} INFO - [2019-04-29 10:31:24,669] {jobs.py:2527} INFO - Task exited with return code 0
