[2019-04-29 20:29:13,205] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: local_sensor.rename_file 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 20:29:13,209] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: local_sensor.rename_file 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 20:29:13,209] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 20:29:13,209] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-29 20:29:13,209] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 20:29:13,217] {__init__.py:1374} INFO - Executing <Task(BashOperator): rename_file> on 2019-04-28T00:00:00+00:00
[2019-04-29 20:29:13,217] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'local_sensor', 'rename_file', '2019-04-28T00:00:00+00:00', '--job_id', '175', '--raw', '-sd', 'DAGS_FOLDER/first_dag.py', '--cfg_path', '/tmp/tmp2s8udc3g']
[2019-04-29 20:29:13,475] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-29 20:29:13,475] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   FutureWarning,
[2019-04-29 20:29:13,621] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file [2019-04-29 20:29:13,621] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 20:29:13,769] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file [2019-04-29 20:29:13,769] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/first_dag.py
[2019-04-29 20:29:13,778] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file [2019-04-29 20:29:13,778] {cli.py:517} INFO - Running <TaskInstance: local_sensor.rename_file 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 20:29:13,785] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2019-04-29 20:29:13,785] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=local_sensor
AIRFLOW_CTX_TASK_ID=rename_file
AIRFLOW_CTX_EXECUTION_DATE=2019-04-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-28T00:00:00+00:00
[2019-04-29 20:29:13,786] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmp56xffv6d/rename_filefpwa1vi1
[2019-04-29 20:29:13,786] {bash_operator.py:114} INFO - Running command: $AIRFLOW_HOME/mv local_file.txt $AIRFLOW_HOME/local_file.bak
[2019-04-29 20:29:13,789] {bash_operator.py:123} INFO - Output:
[2019-04-29 20:29:13,791] {bash_operator.py:127} INFO - /tmp/airflowtmp56xffv6d/rename_filefpwa1vi1: line 1: /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/mv: No such file or directory
[2019-04-29 20:29:13,791] {bash_operator.py:131} INFO - Command exited with return code 127
[2019-04-29 20:29:13,795] {__init__.py:1580} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-04-29 20:29:13,796] {__init__.py:1611} INFO - Marking task as FAILED.
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file Traceback (most recent call last):
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/bin/airflow", line 32, in <module>
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     args.func(args)
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     return f(*args, **kwargs)
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     _run(args, dag, ti)
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     pool=args.pool,
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     return func(*args, **kwargs)
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     result = task_copy.execute(context=context)
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file     raise AirflowException("Bash command failed")
[2019-04-29 20:29:13,808] {base_task_runner.py:101} INFO - Job 175: Subtask rename_file airflow.exceptions.AirflowException: Bash command failed
[2019-04-29 20:29:18,231] {logging_mixin.py:95} INFO - [2019-04-29 20:29:18,230] {jobs.py:2562} INFO - Task exited with return code 1
