[2019-04-29 14:56:43,200] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: demo_XCOM3.t_pull_via_return 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 14:56:43,204] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: demo_XCOM3.t_pull_via_return 2019-04-28T00:00:00+00:00 [queued]>
[2019-04-29 14:56:43,204] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 14:56:43,204] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2019-04-29 14:56:43,204] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2019-04-29 14:56:43,212] {__init__.py:1374} INFO - Executing <Task(PythonOperator): t_pull_via_return> on 2019-04-28T00:00:00+00:00
[2019-04-29 14:56:43,213] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'demo_XCOM3', 't_pull_via_return', '2019-04-28T00:00:00+00:00', '--job_id', '175', '--raw', '-sd', 'DAGS_FOLDER/XCOM_challenge.py', '--cfg_path', '/tmp/tmp9js98i9y']
[2019-04-29 14:56:43,478] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return /home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/configuration.py:214: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
[2019-04-29 14:56:43,479] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   FutureWarning,
[2019-04-29 14:56:43,641] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return [2019-04-29 14:56:43,641] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-04-29 14:56:43,808] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return [2019-04-29 14:56:43,807] {__init__.py:305} INFO - Filling up the DagBag from /home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/XCOM_challenge.py
[2019-04-29 14:56:43,951] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return [2019-04-29 14:56:43,951] {cli.py:517} INFO - Running <TaskInstance: demo_XCOM3.t_pull_via_return 2019-04-28T00:00:00+00:00 [running]> on host localhost.localdomain
[2019-04-29 14:56:43,956] {python_operator.py:104} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=demo_XCOM3
AIRFLOW_CTX_TASK_ID=t_pull_via_return
AIRFLOW_CTX_EXECUTION_DATE=2019-04-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-28T00:00:00+00:00
[2019-04-29 14:56:43,956] {__init__.py:1580} ERROR - 'ti'
Traceback (most recent call last):
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 112, in execute
    return_value = self.execute_callable()
  File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 117, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/XCOM_challenge.py", line 18, in pull_via_return
    task_instance = kwargs["ti"]
KeyError: 'ti'
[2019-04-29 14:56:43,957] {__init__.py:1611} INFO - Marking task as FAILED.
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return Traceback (most recent call last):
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/bin/airflow", line 32, in <module>
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     args.func(args)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     return f(*args, **kwargs)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     _run(args, dag, ti)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     pool=args.pool,
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     return func(*args, **kwargs)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     result = task_copy.execute(context=context)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 112, in execute
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     return_value = self.execute_callable()
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/anaconda3/envs/airflow4/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 117, in execute_callable
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return   File "/home/mjcarleb/HESWork/CSCI-E29/2019sp-airflow_project-mjcarleb/dags/XCOM_challenge.py", line 18, in pull_via_return
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return     task_instance = kwargs["ti"]
[2019-04-29 14:56:43,970] {base_task_runner.py:101} INFO - Job 175: Subtask t_pull_via_return KeyError: 'ti'
[2019-04-29 14:56:48,216] {logging_mixin.py:95} INFO - [2019-04-29 14:56:48,216] {jobs.py:2562} INFO - Task exited with return code 1
